TIERS = {
    "free": {
        "name": "Free",
        "price_inr": 0,
        "daily_tokens": 10_000,
        "monthly_tokens": 100_000,
        "max_tokens_per_request": 800,
        "models": [
            "meta-llama/llama-3.1-8b-instruct:free",
            "google/gemini-flash-1.5:free",
        ],
        "attachments": False,
        "tools": False,
        "concurrent_requests": 1,
    },
    "premium": {
        "name": "Premium",
        "price_inr": 499,
        "daily_tokens": 200_000,
        "monthly_tokens": 3_000_000,
        "max_tokens_per_request": 4000,
        "models": ["*"],
        "attachments": True,
        "tools": True,
        "concurrent_requests": 3,
    },
    "pro": {
        "name": "Pro",
        "price_inr": 1499,
        "daily_tokens": 1_000_000,
        "monthly_tokens": 20_000_000,
        "max_tokens_per_request": 8000,
        "models": ["*"],
        "attachments": True,
        "tools": True,
        "concurrent_requests": 10,
    },
}
