"""fix all models

Revision ID: 71eeb219e6a3
Revises: b0c5baadbf9a
Create Date: 2026-09-09 20:28:27.364533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '71eeb219e6a3'
down_revision: Union[str, Sequence[str], None] = 'b0c5baadbf9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_id'), 'memories', ['id'], unique=False)
    op.drop_index(op.f('ix_snapshots_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_project_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('idx_project_chat_deleted'), table_name='projects')
    op.drop_index(op.f('idx_project_user_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_chat_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_conversation_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('idx_otp_email'), table_name='otps')
    op.drop_index(op.f('idx_otp_email_purpose'), table_name='otps')
    op.drop_index(op.f('idx_otp_expires'), table_name='otps')
    op.drop_index(op.f('idx_otp_is_used'), table_name='otps')
    op.drop_index(op.f('idx_otp_verification_token'), table_name='otps')
    op.drop_index(op.f('ix_otps_email'), table_name='otps')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_build_logs_id'), table_name='build_logs')
    op.drop_index(op.f('ix_build_logs_project_id'), table_name='build_logs')
    op.drop_table('build_logs')
    op.drop_index(op.f('idx_file_project_filename'), table_name='files')
    op.drop_index(op.f('idx_file_project_path'), table_name='files')
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_path'), table_name='files')
    op.drop_index(op.f('ix_files_project_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_user_memories_category'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_project_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_user_id'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_user_project'), table_name='user_memories')
    op.drop_index(op.f('ix_user_memories_user_type'), table_name='user_memories')
    op.drop_table('user_memories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_memories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=9), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=255), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_memories_user_type'), 'user_memories', ['user_id', 'type'], unique=False)
    op.create_index(op.f('ix_user_memories_user_project'), 'user_memories', ['user_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_user_memories_user_id'), 'user_memories', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_memories_project_id'), 'user_memories', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_memories_id'), 'user_memories', ['id'], unique=False)
    op.create_index(op.f('ix_user_memories_category'), 'user_memories', ['category'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('is_binary', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_project_id'), 'files', ['project_id'], unique=False)
    op.create_index(op.f('ix_files_path'), 'files', ['path'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=False)
    op.create_index(op.f('idx_file_project_path'), 'files', ['project_id', 'path'], unique=False)
    op.create_index(op.f('idx_file_project_filename'), 'files', ['project_id', 'filename'], unique=False)
    op.create_table('build_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('log', sa.TEXT(), nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_logs_project_id'), 'build_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_build_logs_id'), 'build_logs', ['id'], unique=False)
    op.create_table('otps',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('code_hash', sa.VARCHAR(), nullable=False),
    sa.Column('purpose', sa.VARCHAR(length=6), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('is_used', sa.BOOLEAN(), nullable=True),
    sa.Column('attempts', sa.INTEGER(), nullable=True),
    sa.Column('resend_count', sa.INTEGER(), nullable=True),
    sa.Column('verification_token', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_index(op.f('ix_otps_email'), 'otps', ['email'], unique=False)
    op.create_index(op.f('idx_otp_verification_token'), 'otps', ['verification_token'], unique=False)
    op.create_index(op.f('idx_otp_is_used'), 'otps', ['is_used'], unique=False)
    op.create_index(op.f('idx_otp_expires'), 'otps', ['expires_at'], unique=False)
    op.create_index(op.f('idx_otp_email_purpose'), 'otps', ['email', 'purpose'], unique=False)
    op.create_index(op.f('idx_otp_email'), 'otps', ['email'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('chat_id', sa.INTEGER(), nullable=False),
    sa.Column('conversation_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('workspace', sa.VARCHAR(length=50), nullable=True),
    sa.Column('framework', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('preview_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_conversation_id'), 'projects', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_projects_chat_id'), 'projects', ['chat_id'], unique=False)
    op.create_index(op.f('idx_project_user_status'), 'projects', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_project_chat_deleted'), 'projects', ['chat_id', 'is_deleted'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('state', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_project_id'), 'snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_snapshots_id'), 'snapshots', ['id'], unique=False)
    op.drop_index(op.f('ix_memories_id'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
